# Generated by Django 5.2.11 on 2026-02-19 09:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('CLIENT', 'Client'), ('SPECIALIST', 'Specialist')], default='CLIENT', max_length=20)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(default='Ташкент', max_length=100)),
                ('favorites', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SpecialistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Ремонт', 'Ремонт'), ('Репетиторы', 'Репетиторы'), ('Уборка', 'Уборка'), ('IT и фриланс', 'IT и фриланс'), ('Красота', 'Красота'), ('Перевозки', 'Перевозки'), ('Бухгалтеры и юристы', 'Бухгалтеры и юристы'), ('Спорт', 'Спорт'), ('Домашний персонал', 'Домашний персонал'), ('Артисты', 'Артисты'), ('Другое', 'Другое')], max_length=50)),
                ('rating', models.FloatField(default=5.0)),
                ('reviews_count', models.IntegerField(default=0)),
                ('price_start', models.DecimalField(decimal_places=0, max_digits=12)),
                ('description', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('tags', models.JSONField(default=list)),
                ('telegram', models.CharField(blank=True, max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Ремонт', 'Ремонт'), ('Репетиторы', 'Репетиторы'), ('Уборка', 'Уборка'), ('IT и фриланс', 'IT и фриланс'), ('Красота', 'Красота'), ('Перевозки', 'Перевозки'), ('Бухгалтеры и юристы', 'Бухгалтеры и юристы'), ('Спорт', 'Спорт'), ('Домашний персонал', 'Домашний персонал'), ('Артисты', 'Артисты'), ('Другое', 'Другое')], max_length=50)),
                ('budget', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('date_info', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('OPEN', 'В поиске'), ('IN_PROGRESS', 'В работе'), ('COMPLETED', 'Завершен'), ('CANCELED', 'Отменен')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.specialistprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.task')),
            ],
        ),
    ]
