# Generated by Django 5.2.11 on 2026-02-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialistprofile',
            name='passport_image',
            field=models.ImageField(blank=True, null=True, upload_to='specialist_documents/'),
        ),
        migrations.AddField(
            model_name='specialistprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='specialist_avatars/'),
        ),
    ]
