# Generated by Django 5.2.11 on 2026-02-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_specialistprofile_passport_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialistprofile',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
