# Generated by Django 5.2.11 on 2026-02-20 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_emailverification_expires_at_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialistprofile',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('TOP_UP', 'Пополнение баланса'), ('RESPONSE_FEE', 'Плата за отклик'), ('DEAL_FEE', 'Комиссия за сделку')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('SUCCESS', 'Успешно'), ('FAILED', 'Ошибка'), ('CANCELED', 'Отменен')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
