# Generated by Django 5.2.11 on 2026-02-20 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_specialistprofile_balance_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('score_overall', models.PositiveSmallIntegerField(default=5)),
                ('score_punctuality', models.PositiveSmallIntegerField(default=5)),
                ('score_quality', models.PositiveSmallIntegerField(default=5)),
                ('score_friendliness', models.PositiveSmallIntegerField(default=5)),
                ('score_honesty', models.PositiveSmallIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_reviews', to=settings.AUTH_USER_MODEL)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.specialistprofile')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='api.task')),
            ],
            options={
                'unique_together': {('author', 'task')},
            },
        ),
    ]
