# Generated by Django 5.2.11 on 2026-02-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='budget',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_info',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
