import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ru' | 'uz';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations = {
  ru: {
    // Header & Nav
    "client": "Я Клиент",
    "specialist": "Я Специалист",
    "iAmClient": "Я Заказчик",
    "iAmSpecialist": "Я Специалист",
    "catalog": "Каталог",
    "createOrder": "Создать заказ",
    "findOrders": "Найти заказы",
    "myResponses": "Мои отклики",
    "becomeSpecialist": "Стать специалистом",
    "login": "Войти",
    "logout": "Выйти",
    "messages": "Сообщения",
    "main": "Главная",
    "search": "Поиск",
    "chats": "Чаты",
    "profile": "Профиль",
    "orders": "Заказы",
    "myProfile": "Мой профиль",

    // Home
    "heroTitle": "Найдите специалиста \nдля любой задачи",
    "heroSubtitle": "150 000+ проверенных мастеров с отзывами и рейтингом в г.",
    "searchPlaceholder": "Сантехник, репетитор, уборка...",
    "find": "Найти",
    "popular": "Часто ищут:",
    "popularCategories": "Популярные категории",
    "allServices": "Все услуги",
    "trustTitle": "Maestro — это надежно",
    "trust1Title": "Проверенные профи",
    "trust1Desc": "Мы проверяем паспорта и сертификаты специалистов. Смотрите значок \"Проверен\".",
    "trust2Title": "Честные отзывы",
    "trust2Desc": "2 млн+ отзывов от реальных клиентов. Мы публикуем все: и хорошие, и плохие.",
    "trust3Title": "Безопасная оплата",
    "trust3Desc": "Вы платите напрямую мастеру после выполнения работы. Никаких скрытых комиссий сервиса.",
    "footerDesc": "Сервис поиска специалистов в Узбекистане",
    "aboutService": "О сервисе",
    "help": "Помощь",
    "rules": "Правила",
    "rights": "Все права защищены.",
    "tashkent": "Ташкент",

    // Catalog Page
    "catalogLabel": "КАТАЛОГ УСЛУГ",
    "catalogTitle": "Все услуги Maestro",
    "catalogSubtitle": "Выбирайте из тысяч проверенных специалистов в сотнях категорий. От мелкого ремонта до обучения языкам.",
    "notFoundTitle": "Не нашли нужную услугу?",
    "notFoundDesc": "Воспользуйтесь умным поиском или создайте заказ, описав задачу своими словами. Мы подберем специалиста даже для нестандартных задач.",
    "viewAll": "Смотреть все",

    // Search Page
    "foundSpecialists": "Найдено {{count}} специалистов",
    "viewList": "Списком",
    "viewMap": "На карте",
    "aiSearchLoading": "Ищем подходящих профи...",
    "aiSearchAnalyzing": "Анализируем категории, теги и рейтинг.",
    "aiSummary": "AI Подбор",
    "aiRequest": "Запрос",
    "aiPriceRef": "Ориентир цены",
    "aiFilters": "Фильтры",
    "reset": "Сброс",
    "resetFilters": "Сбросить фильтры",
    "noSpecialistsFound": "К сожалению, по вашему запросу специалистов не найдено. Попробуйте изменить категорию.",
    "noSpecialistsTags": "Нет специалистов с выбранными тегами. Попробуйте сбросить фильтры.",
    "viewProfile": "Посмотреть профиль",
    "priceFrom": "от {{price}} UZS",
    "addToFavoritesTooltip": "Добавить в избранное",
    "removeFromFavoritesTooltip": "Удалить из избранного",

    // Detailed Directory Items (from constants.ts)
    "Мастера по ремонту": "Мастера по ремонту",
    "Мастера красоты": "Мастера красоты",
    "Фрилансеры": "Фрилансеры",
    "Спортивные тренеры": "Спортивные тренеры",
    
    // Sub-items
    "Начальная школа": "Начальная школа",
    "Подготовка к школе": "Подготовка к школе",
    "Музыка": "Музыка",
    "Штукатуры": "Штукатуры",
    "Ремонт под ключ": "Ремонт под ключ",
    "Мелкий бытовой ремонт": "Мелкий бытовой ремонт",
    "Макияж": "Макияж",
    "Причёски": "Причёски",
    "Эпиляция": "Эпиляция",
    "Стилисты": "Стилисты",
    "Косметология": "Косметология",
    "Дизайнеры": "Дизайнеры",
    "Маркетинг": "Маркетинг",
    "Работа с текстами": "Работа с текстами",
    "Системные администраторы": "Системные администраторы",
    "IT-аутсорсинг": "IT-аутсорсинг",
    "Разработка сайтов": "Разработка сайтов",
    "Юристы": "Юристы",
    "Бухгалтеры": "Бухгалтеры",
    "Риелторы": "Риелторы",
    "Бизнес-консультанты": "Бизнес-консультанты",
    "Кадровики": "Кадровики",
    "Фитнес": "Фитнес",
    "Йога": "Йога",
    "Пилатес": "Пилатес",
    "Стретчинг": "Стретчинг",
    "Бокс": "Бокс",
    "Плавание": "Плавание",
    "Домработницы": "Домработницы",
    "Водители": "Водители",
    "Няни": "Няни",
    "Сиделки": "Сиделки",
    "Повара": "Повара",
    "Музыканты": "Музыканты",
    "Танцоры": "Танцоры",
    "Ведущие": "Ведущие",
    "Фокусники": "Фокусники",
    "Аниматоры": "Аниматоры",

    // Create Task
    "findSpecialistTitle": "Найти специалиста",
    "describeTask": "Опишите задачу, и мы подберем лучших мастеров.",
    "taskPlaceholder": "Что нужно сделать? Например: протекает труба на кухне...",
    "analyze": "Анализируем...",
    "continue": "Продолжить",
    "taskDetails": "Уточните детали",
    "taskName": "Название задачи",
    "taskDesc": "Описание",
    "aiImprove": "AI Улучшить",
    "budget": "Бюджет",
    "district": "Район",
    "back": "Назад",
    "findMasters": "Найти мастеров",
    "matchingPros": "Подбираем специалистов...",
    "recommendedPros": "Рекомендуемые профи",
    "publishAll": "Опубликовать для всех",
    "sendToMasters": "Отправить мастерам",

    // Specialist Dashboard
    "taskBoard": "Биржа заказов",
    "foundActiveOrders": "Найдено {{count}} активных заказов",
    "hideFilters": "Скрыть фильтры",
    "showFilters": "Фильтры",
    "smartSearchPlaceholder": "Умный поиск: например, 'нужно починить розетку'",
    "aiSearch": "AI Поиск",
    "category": "Категория",
    "allCategories": "Все категории",
    "allUzbekistan": "Весь Узбекистан",
    "minBudget": "Мин. бюджет (UZS)",
    "resetAll": "Сбросить все",
    "aiMatching": "AI Подбор",
    "tags": "Теги",
    "getMoreOrders": "Получайте больше заказов",
    "verifyDocsDesc": "Подтвердите документы и пройдите проверку, чтобы получить галочку \"Проверен\".",
    "getVerified": "Пройти проверку",
    "statistics": "Статистика",
    "availableResponses": "Доступно откликов",
    "profileViews": "Просмотров профиля",
    "rating": "Рейтинг",
    "youResponded": "Вы откликнулись",
    "respond": "Откликнуться",
    "responseSent": "Отклик отправлен",
    "noTasksFound": "Заказов не найдено",
    "aiNoTasksDesc": "AI не нашел заказов в этой категории. Попробуйте уточнить запрос или сбросить поиск.",
    "noTasksFilterDesc": "Попробуйте изменить параметры фильтрации или поисковый запрос.",
    "responseToTask": "Отклик на заказ",
    "offerPrice": "Предложите вашу цену (UZS)",
    "coverLetter": "Сопроводительное письмо",
    "coverLetterPlaceholder": "Напишите, почему стоит выбрать вас...",
    "sendResponse": "Отправить отклик",
    "sending": "Отправка...",

    // Specialist Details
    "specialistNotFound": "Специалист не найден",
    "goBack": "Вернуться назад",
    "verifiedPassport": "Паспорт проверен",
    "verifiedPhone": "Телефон подтвержден",
    "reviewsCount": "отзывов",
    "selectSpecialist": "Выбрать специалиста",
    "writeToChat": "Написать в чат",
    "chatNotice": "Специалист увидит ваш номер только после вашего согласия.",
    "inFavorites": "В избранном",
    "addToFavorites": "В избранное",
    "tabServices": "Услуги и цены",
    "tabReviews": "Отзывы",
    "tabPortfolio": "Примеры работ",
    "tabAbout": "О себе",
    "priceList": "Прайс-лист",
    "priceDisclaimer": "Итоговая стоимость может измениться после диагностики и уточнения деталей заказа.",
    "aboutSpecialist": "О специалисте",
    "noDescription": "Специалист не добавил подробного описания.",
    "skills": "Навыки",
    "photos": "Фото работ",
    "showMoreReviews": "Показать еще отзывы",
    "write": "Написать",
    "free": "Бесплатно",
    "from": "от",
    "urgent": "Срочный выезд",
    "consultation": "Консультация",
    "homeVisit": "Выезд на дом",
    "diagnostic": "Диагностика",
    "mainWork": "Основная работа (час)",

    // Profile
    "myOrders": "Мои заказы",
    "orderHistory": "История заказов",
    "settings": "Настройки",
    "favorites": "Избранные",
    "activeOrders": "Активные заказы",
    "completedOrders": "Заказов выполнено",
    "avgRating": "Средняя оценка",
    "exp": "Опыт работы",
    "aboutMe": "О себе",
    "servicesAndSkills": "Услуги и навыки",
    "serviceCost": "Стоимость услуг",
    "minVisit": "Минимальный выезд",
    "noActiveOrders": "Нет активных заказов",
    "createOrderToFind": "Создайте заказ, чтобы найти специалиста",
    "createNow": "Создать сейчас",
    "historyEmpty": "История пуста",
    "historyEmptyDesc": "Здесь будут отображаться ваши завершенные заказы",
    "favoritesEmpty": "Список пуст",
    "favoritesEmptyDesc": "Добавляйте понравившихся специалистов в избранное, чтобы не потерять их",
    "findSpecialists": "Найти специалистов",
    "editProfile": "Редактировать профиль",
    "updateInfo": "Обновите свои личные данные и настройки",
    "mainInfo": "Основная информация",
    "yourName": "Ваше имя",
    "city": "Город",
    "professionalData": "Профессиональные данные",
    "skillsTags": "Навыки (теги)",
    "demoVerified": "Демонстрация: Статус \"Проверенный специалист\"",
    "save": "Сохранить",
    "cancel": "Отмена",
    "all": "Все",
    "completed": "Завершенные",
    "canceled": "Отмененные",
    "verified": "Проверен",
    "searchIn": "В поиске",
    "inProgress": "В работе",
    "completedStatus": "Завершен",
    "canceledStatus": "Отменен",
    "favoriteSpecialists": "Избранные специалисты",
    "minCost": "Мин. стоимость (UZS)",
    "email": "Email",
    "phone": "Телефон",
    "contact": "Контакты",
    "experienceYears": "г.", // years
    "reviews": "отзывов",

    // Categories Mappings
    "Сантехника": "Сантехника",
    "Психология": "Психология",
    "Математика": "Математика",
    "Английский язык": "Английский язык",
    "Электрика": "Электрика",
    "Плиточники": "Плиточники",
    "Двери": "Двери",
    "Русский язык": "Русский язык",

    "Уборка квартиры": "Уборка квартиры",
    "Репетитор по математике": "Репетитор по математике",
    "Сантехник": "Сантехник",
    "Мастер на час": "Мастер на час",
    "Маникюр": "Маникюр",

    // Service Categories Enum
    "Ремонт": "Ремонт",
    "Репетиторы": "Репетиторы",
    "Уборка": "Уборка",
    "IT и фриланс": "IT и фриланс",
    "Красота": "Красота",
    "Перевозки": "Перевозки",
    "Бухгалтеры и юристы": "Бухгалтеры и юристы",
    "Спорт": "Спорт",
    "Домашний персонал": "Домашний персонал",
    "Артисты": "Артисты",
    "Другое": "Другое",

    // Locations & Districts
    "Ташкент": "Toshkent",
    "Ташкент, Юнусабад": "Toshkent, Yunusobod",
    "Ташкент, Чиланзар": "Toshkent, Chilonzor",
    "Ташкент, Мирзо-Улугбек": "Toshkent, Mirzo Ulug'bek",
    "Ташкент, Сергели": "Toshkent, Sergeli",
    "Ташкент, Мирабад": "Toshkent, Mirobod",
    "Ташкент, Яккасарай": "Toshkent, Yakkasaroy",
    "Ташкент, Ойбек": "Toshkent, Oybek",
    "Ташкент, Центр": "Toshkent, Markaz",
    "Ташкент, Шайхантахур": "Toshkent, Shayxontohur",
    "Ташкент, Экопарк": "Toshkent, Ekopark",
    "Самарканд": "Samarqand",
    "Бухара": "Buxoro",
    "Андижан": "Andijon",
    "Наманган": "Namangan",
    "Фергана": "Farg'ona",
    "Нукус": "Nukus",
    "Удаленно": "Masofadan",
    "Удаленно / Ташкент": "Masofadan / Toshkent",

    // Tags
    "Трубы": "Quvurlar",
    "Электрик": "Elektrik",
    "Сборка мебели": "Mebel yig'ish",
    "Монтаж": "Montaj",
    "Люстры": "Qandillar",
    "Водопровод": "Suv quvurlari",
    "Прически": "Soch turmagi",
    "Свадьба": "To'y",
    "Гель-лак": "Gel-lak",
    "Барбер": "Barber",
    "Стрижки": "Soch kesish",
    "Борода": "Soqol",
    "Сайты": "Saytlar",
    "SMM": "SMM",
    "Таргет": "Target",
    "Дизайн": "Dizayn",
    "Логотипы": "Logotiplar",
    "Figma": "Figma",
    "Тексты": "Matnlar",
    "Копирайтинг": "Kopirayting",
    "Переводы": "Tarjimalar",
    "Бухгалтер": "Buxgalter",
    "Отчетность": "Hisobotlar",
    "Аутсорсинг": "Autsorsing",
    "Юрист": "Yurist",
    "Консультация": "Maslahat",
    "Суд": "Sud",
    "Похудение": "Ozish",
    "Бодибилдинг": "Bodibilding",
    "Здоровье": "Sog'liq",
    "Няня": "Enaga",
    "Дети": "Bolalar",
    "Помощница": "Yordamchi",
    "Химчистка": "Kimyoviy tozalash",
    "Мойка окон": "Deraza yuvish",
    "Водитель": "Haydovchi",
    "DJ": "DJ",
    "Фокусы": "Fokuslar",
    "Праздник": "Bayram",
    "Аниматор": "Animator",
    "IELTS": "IELTS",
    "Физика": "Fizika",
    "Фортепиано": "Fortepiano",

    // Specialist Descriptions
    "Репетитор по английскому языку (IELTS 8.5). Готовлю к поступлению в Вестминстер и ИНХА.": "Ingliz tili repetitori (IELTS 8.5). Westminster va INHA universitetlariga kirishga tayyorlayman.",
    "Математика для школьников 5-11 классов. Подготовка к ЕГЭ и ДТМ. Индивидуальный подход.": "5-11 sinf o'quvchilari uchun matematika. DTM ga tayyorgarlik. Individual yondashuv.",
    "Преподаватель фортепиано и сольфеджио. Опыт работы в консерватории 10 лет.": "Fortepiano va solfedjio o'qituvchisi. Konservatoriyada 10 yillik ish tajribasi.",
    "Опытный сантехник. Монтаж полипропиленовых труб, установка душевых кабин, ремонт смесителей. Работаю 24/7.": "Tajribali santexnik. Polipropilen quvurlarni montaj qilish, dush kabinalarini o'rnatish, kranlarni ta'mirlash. 24/7 ishlayman.",
    "Мастер универсал. Сантехника, электрика, сборка мебели. Опыт 10 лет. Даю гарантию.": "Universal usta. Santexnika, elektrika, mebel yig'ish. 10 yillik tajriba. Kafolat beraman.",
    "Профессиональный электрик с допуском. Монтаж проводки, установка люстр, щитков.": "Ruxsatnomaga ega professional elektrik. Simlarni montaj qilish, qandillar va shitlarni o'rnatish.",
    "Сантехник. Устранение засоров, установка смесителей, унитазов, ванн. Быстро и чисто.": "Santexnik. Tiqilib qolishlarni bartaraf etish, kranlar, unitazlar, vannalarni o'rnatish. Tez va toza.",
    "Визажист, стилист по прическам. Свадебный образ, вечерний макияж.": "Vizajist, soch turmagi ustasi. To'y obrazlari, oqshom makiyaji.",
    "Маникюр, педикюр, наращивание ногтей. Стерильные инструменты.": "Manikyur, pedikyur, tirnoq o'stirish. Steril asboblar.",
    "Мужские стрижки, оформление бороды. Выезд на дом.": "Erkaklar soch turmagi, soqol tekislash. Uyga borish xizmati.",
    "Разработка сайтов, настройка рекламы в Instagram и Telegram. Создание лендингов.": "Saytlar yaratish, Instagram va Telegram reklamalarini sozlash. Lendinglar yaratish.",
    "Графический дизайнер. Логотипы, фирменный стиль, баннеры, презентации.": "Grafik dizayner. Logotiplar, korporativ uslub, bannerlar, taqdimotlar.",
    "Написание продающих текстов для Instagram, статьи для сайтов, переводы RU/UZ/EN.": "Instagram uchun sotuvchi matnlar yozish, saytlar uchun maqolalar, RU/UZ/EN tarjimalari.",
    "Бухгалтерское сопровождение бизнеса, сдача отчетов, открытие ООО и ИП.": "Biznesni buxgalteriya hisobi bilan ta'minlash, hisobotlarni topshirish, MChJ va YaTT ochish.",
    "Юридические консультации. Семейное право, наследство, споры с застройщиками.": "Yuridik maslahatlar. Oila huquqi, meros, quruvchilar bilan nizolar.",
    "Персональный тренер по бодибилдингу и фитнесу. Составление программ питания.": "Bodibilding va fitnes bo'yicha shaxsiy murabbiy. Ovqatlanish dasturlarini tuzish.",
    "Инструктор по Хатха-йоге и стретчингу. Групповые и индивидуальные занятия.": "Hatha-yoga va stretching instruktori. Guruh va individual mashg'ulotlar.",
    "Няня для детей от 1 года. Добрая, ответственная, есть педагогическое образование.": "1 yoshdan oshgan bolalar uchun enaga. Mehribon, mas'uliyatli, pedagogik ma'lumotga ega.",
    "Профессиональная уборка квартир и офисов. Химчистка мягкой мебели.": "Kvartiralar va ofislarni professional tozalash. Yumshoq mebellarni kimyoviy tozalash.",
    "Личный водитель на своем авто (Malibu 2). Стаж вождения 15 лет. Пунктуальный.": "Shaxsiy avtomobilda haydovchi (Malibu 2). 15 yillik haydovchilik tajribasi. Mas'uliyatli.",
    "Музыкальное сопровождение свадеб, корпоративов, дней рождения. Своя аппаратура.": "To'ylar, korporativlar, tug'ilgan kunlarda musiqiy xizmat. Shaxsiy apparatura.",
    "Иллюзионист на детские праздники и взрослые мероприятия. Интерактивная программа.": "Bolalar bayramlari va kattalar tadbirlari uchun illyuzionist. Interaktiv dastur.",
  },
  uz: {
    // Header & Nav
    "client": "Men Mijozman",
    "specialist": "Men Ustaman",
    "iAmClient": "Men Buyurtmachi",
    "iAmSpecialist": "Men Mutaxassis",
    "catalog": "Katalog",
    "createOrder": "Buyurtma berish",
    "findOrders": "Buyurtmalarni topish",
    "myResponses": "Mening takliflarim",
    "becomeSpecialist": "Usta bo'lish",
    "login": "Kirish",
    "logout": "Chiqish",
    "messages": "Xabarlar",
    "main": "Asosiy",
    "search": "Qidiruv",
    "chats": "Chatlar",
    "profile": "Profil",
    "orders": "Buyurtmalar",
    "myProfile": "Mening profilim",

    // Home
    "heroTitle": "Istalgan vazifa uchun \nmutaxassis toping",
    "heroSubtitle": "150 000+ tekshirilgan ustalar, sharhlar va reytinglar bilan.",
    "searchPlaceholder": "Santexnik, repetitor, tozalash...",
    "find": "Topish",
    "popular": "Ko'p qidiriladigan:",
    "popularCategories": "Mashhur kategoriyalar",
    "allServices": "Barcha xizmatlar",
    "trustTitle": "Maestro — bu ishonchli",
    "trust1Title": "Tekshirilgan ustalar",
    "trust1Desc": "Biz mutaxassislarning pasport va sertifikatlarini tekshiramiz. \"Tekshirilgan\" belgisiga qarang.",
    "trust2Title": "Haqiqiy sharhlar",
    "trust2Desc": "2 mln+ haqiqiy mijozlar sharhlari. Biz hammasini chop etamiz: yaxshisini ham, yomonini ham.",
    "trust3Title": "Xavfsiz to'lov",
    "trust3Desc": "Siz ish bajarilgandan so'ng to'g'ridan-to'g'ri ustaga to'laysiz. Yashirin komissiyalar yo'q.",
    "footerDesc": "O'zbekistonda mutaxassislarni izlash xizmati",
    "aboutService": "Xizmat haqida",
    "help": "Yordam",
    "rules": "Qoidalar",
    "rights": "Barcha huquqlar himoyalangan.",
    "tashkent": "Toshkent",

    // Catalog Page
    "catalogLabel": "XIZMATLAR KATALOGI",
    "catalogTitle": "Maestro barcha xizmatlari",
    "catalogSubtitle": "Yuzlab toifadagi minglab tekshirilgan mutaxassislarni tanlang. Kichik ta'mirlashdan tortib til o'rganishgacha.",
    "notFoundTitle": "Kerakli xizmatni topmadingizmi?",
    "notFoundDesc": "Aqlli qidiruvdan foydalaning yoki vazifani o'z so'zlaringiz bilan tasvirlab buyurtma yarating. Biz hatto nostandart vazifalar uchun ham mutaxassis topamiz.",
    "viewAll": "Hammasini ko'rish",

    // Search Page
    "foundSpecialists": "Topilgan mutaxassislar: {{count}}",
    "viewList": "Ro'yxat",
    "viewMap": "Xaritada",
    "aiSearchLoading": "Mos mutaxassislar qidirilmoqda...",
    "aiSearchAnalyzing": "Kategoriyalar, teglar va reyting tahlil qilinmoqda.",
    "aiSummary": "AI Saralash",
    "aiRequest": "So'rov",
    "aiPriceRef": "Narx mo'ljali",
    "aiFilters": "Filtrlar",
    "reset": "Tozalash",
    "resetFilters": "Filtrlarni tozalash",
    "noSpecialistsFound": "Afsuski, so'rovingiz bo'yicha mutaxassislar topilmadi. Kategoriyani o'zgartirib ko'ring.",
    "noSpecialistsTags": "Tanlangan teglar bo'yicha mutaxassislar yo'q. Filtrlarni tozalab ko'ring.",
    "viewProfile": "Profilni ko'rish",
    "priceFrom": "{{price}} UZS dan",
    "addToFavoritesTooltip": "Sevimlilarga qo'shish",
    "removeFromFavoritesTooltip": "Sevimlilardan o'chirish",

    // Detailed Directory Items
    "Мастера по ремонту": "Ta'mirlash ustalari",
    "Мастера красоты": "Go'zallik ustalari",
    "Фрилансеры": "Frilanserlar",
    "Спортивные тренеры": "Sport murabbiylari",

    // Sub-items
    "Начальная школа": "Boshlang'ich maktab",
    "Подготовка к школе": "Maktabga tayyorgarlik",
    "Музыка": "Musiqa",
    "Штукатуры": "Suvoqchilar",
    "Ремонт под ключ": "Kalitgacha ta'mirlash",
    "Мелкий бытовой ремонт": "Mayda maishiy ta'mirlash",
    "Макияж": "Pardoz",
    "Причёски": "Soch turmagi",
    "Эпиляция": "Epilyatsiya",
    "Стилисты": "Stilistlar",
    "Косметология": "Kosmetologiya",
    "Дизайнеры": "Dizaynerlar",
    "Маркетинг": "Marketing",
    "Работа с текстами": "Matnlar bilan ishlash",
    "Системные администраторы": "Tizim administratorlari",
    "IT-аутсорсинг": "IT-autsorsing",
    "Разработка сайтов": "Saytlar yaratish",
    "Юристы": "Yuristlar",
    "Бухгалтеры": "Buxgalterlar",
    "Риелторы": "Rieltorlar",
    "Бизнес-консультанты": "Biznes-konsultantlar",
    "Кадровики": "Kadrlar bo'limi",
    "Фитнес": "Fitnes",
    "Йога": "Yoga",
    "Пилатес": "Pilates",
    "Стретчинг": "Stretching",
    "Бокс": "Boks",
    "Плавание": "Suzish",
    "Домработницы": "Uy xizmatchilari",
    "Водители": "Haydovchilar",
    "Няни": "Enagalar",
    "Сиделки": "Parvarishchilar",
    "Повара": "Oshpazlar",
    "Музыканты": "Musiqachilar",
    "Танцоры": "Raqqisalar",
    "Ведущие": "Boshlovchilar",
    "Фокусники": "Fokusçilar",
    "Аниматоры": "Animatorlar",

    // Create Task
    "findSpecialistTitle": "Mutaxassis topish",
    "describeTask": "Vazifani tavsiflang, biz eng yaxshi ustalarni tanlab beramiz.",
    "taskPlaceholder": "Nima qilish kerak? Masalan: oshxonada quvur oqyapti...",
    "analyze": "Tahlil qilinmoqda...",
    "continue": "Davom etish",
    "taskDetails": "Tafsilotlarni aniqlashtirish",
    "taskName": "Vazifa nomi",
    "taskDesc": "Tavsif",
    "aiImprove": "AI Yaxshilash",
    "budget": "Byudjet",
    "district": "Tuman",
    "back": "Orqaga",
    "findMasters": "Ustalarni topish",
    "matchingPros": "Mutaxassislar tanlanmoqda...",
    "recommendedPros": "Tavsiya etilgan ustalar",
    "publishAll": "Hammaga e'lon qilish",
    "sendToMasters": "Ustalarga yuborish",

    // Specialist Dashboard
    "taskBoard": "Buyurtmalar birjasi",
    "foundActiveOrders": "{{count}} ta faol buyurtma topildi",
    "hideFilters": "Filtrlarni yashirish",
    "showFilters": "Filtrlar",
    "smartSearchPlaceholder": "Aqlli qidiruv: masalan, 'rozetkani tuzatish'",
    "aiSearch": "AI Qidiruv",
    "category": "Kategoriya",
    "allCategories": "Barcha kategoriyalar",
    "allUzbekistan": "Butun O'zbekiston",
    "minBudget": "Min. byudjet (UZS)",
    "resetAll": "Hammasini tozalash",
    "aiMatching": "AI Saralash",
    "tags": "Teglar",
    "getMoreOrders": "Ko'proq buyurtma oling",
    "verifyDocsDesc": "Hujjatlarni tasdiqlang va \"Tekshirilgan\" belgisini olish uchun tekshiruvdan o'ting.",
    "getVerified": "Tekshiruvdan o'tish",
    "statistics": "Statistika",
    "availableResponses": "Mavjud takliflar",
    "profileViews": "Profil ko'rishlar",
    "rating": "Reyting",
    "youResponded": "Siz taklif yubordingiz",
    "respond": "Taklif yuborish",
    "responseSent": "Yuborildi",
    "noTasksFound": "Buyurtmalar topilmadi",
    "aiNoTasksDesc": "AI bu kategoriyada buyurtma topolmadi. So'rovni aniqlashtiring yoki qidiruvni tozalang.",
    "noTasksFilterDesc": "Filtrlash parametrlarini yoki qidiruv so'rovini o'zgartirib ko'ring.",
    "responseToTask": "Buyurtmaga javob",
    "offerPrice": "Narxingizni taklif qiling (UZS)",
    "coverLetter": "Kuzatuv xati",
    "coverLetterPlaceholder": "Nega sizni tanlashlari kerakligini yozing...",
    "sendResponse": "Yuborish",
    "sending": "Yuborilmoqda...",

    // Specialist Details
    "specialistNotFound": "Mutaxassis topilmadi",
    "goBack": "Orqaga qaytish",
    "verifiedPassport": "Pasport tekshirilgan",
    "verifiedPhone": "Telefon tasdiqlangan",
    "reviewsCount": "sharhlar",
    "selectSpecialist": "Mutaxassisni tanlash",
    "writeToChat": "Chatga yozish",
    "chatNotice": "Mutaxassis sizning raqamingizni faqat siz rozi bo'lsangiz ko'radi.",
    "inFavorites": "Sevimlilarda",
    "addToFavorites": "Sevimlilarga",
    "tabServices": "Xizmatlar va narxlar",
    "tabReviews": "Sharhlar",
    "tabPortfolio": "Ish namunalari",
    "tabAbout": "O'zi haqida",
    "priceList": "Narxlar ro'yxati",
    "priceDisclaimer": "Yakuniy narx diagnostika va buyurtma tafsilotlarini aniqlashtirgandan so'ng o'zgarishi mumkin.",
    "aboutSpecialist": "Mutaxassis haqida",
    "noDescription": "Mutaxassis batafsil tavsif qo'shmagan.",
    "skills": "Ko'nikmalar",
    "photos": "Ish rasmlari",
    "showMoreReviews": "Yana sharhlarni ko'rsatish",
    "write": "Yozish",
    "free": "Bepul",
    "from": "dan",
    "urgent": "Tezkor chiqish",
    "consultation": "Konsultatsiya",
    "homeVisit": "Uyga tashrif",
    "diagnostic": "Diagnostika",
    "mainWork": "Asosiy ish (soat)",

    // Profile
    "myOrders": "Buyurtmalarim",
    "orderHistory": "Buyurtmalar tarixi",
    "settings": "Sozlamalar",
    "favorites": "Sevimlilar",
    "activeOrders": "Faol buyurtmalar",
    "completedOrders": "Bajarilgan buyurtmalar",
    "avgRating": "O'rtacha reyting",
    "exp": "Ish tajribasi",
    "aboutMe": "Men haqimda",
    "servicesAndSkills": "Xizmatlar va ko'nikmalar",
    "serviceCost": "Xizmat narxi",
    "minVisit": "Minimal tashrif",
    "noActiveOrders": "Faol buyurtmalar yo'q",
    "createOrderToFind": "Mutaxassis topish uchun buyurtma yarating",
    "createNow": "Hozir yaratish",
    "historyEmpty": "Tarix bo'sh",
    "historyEmptyDesc": "Bu yerda bajarilgan buyurtmalaringiz ko'rsatiladi",
    "favoritesEmpty": "Ro'yxat bo'sh",
    "favoritesEmptyDesc": "Yoqtirgan mutaxassislarni yo'qotmaslik uchun sevimlilarga qo'shing",
    "findSpecialists": "Mutaxassislarni topish",
    "editProfile": "Profilni tahrirlash",
    "updateInfo": "Shaxsiy ma'lumotlar va sozlamalarni yangilang",
    "mainInfo": "Asosiy ma'lumotlar",
    "yourName": "Ismingiz",
    "city": "Shahar",
    "professionalData": "Professional ma'lumotlar",
    "skillsTags": "Ko'nikmalar (teglar)",
    "demoVerified": "Namoyish: \"Tekshirilgan mutaxassis\" statusi",
    "save": "Saqlash",
    "cancel": "Bekor qilish",
    "all": "Barchasi",
    "completed": "Bajarilgan",
    "canceled": "Bekor qilingan",
    "verified": "Tekshirilgan",
    "searchIn": "Qidiruvda",
    "inProgress": "Jarayonda",
    "completedStatus": "Bajarildi",
    "canceledStatus": "Bekor qilindi",
    "favoriteSpecialists": "Sevimli mutaxassislar",
    "minCost": "Min. narx (UZS)",
    "email": "Email",
    "phone": "Telefon",
    "contact": "Kontaktlar",
    "experienceYears": "yil",
    "reviews": "sharhlar",

    // Categories Mappings
    "Сантехника": "Santexnika",
    "Психология": "Psixologiya",
    "Математика": "Matematika",
    "Английский язык": "Ingliz tili",
    "Электрика": "Elektrika",
    "Плиточники": "Plitkachilar",
    "Двери": "Eshiklar",
    "Русский язык": "Rus tili",

    "Уборка квартиры": "Uyni tozalash",
    "Репетитор по математике": "Matematika repetitori",
    "Сантехник": "Santexnik",
    "Мастер на час": "Bir soatlik usta",
    "Маникюр": "Manikyur",

    // Service Categories Enum
    "Ремонт": "Ta'mirlash",
    "Репетиторы": "Repetitorlar",
    "Уборка": "Tozalash",
    "IT и фриланс": "IT va frilans",
    "Красота": "Go'zallik",
    "Перевозки": "Tashish",
    "Бухгалтеры и юристы": "Buxgalterlar va yuristlar",
    "Спорт": "Sport",
    "Домашний персонал": "Uy xodimlari",
    "Артисты": "Artistlar",
    "Другое": "Boshqa",

    // Locations & Districts
    "Ташкент": "Toshkent",
    "Ташкент, Юнусабад": "Toshkent, Yunusobod",
    "Ташкент, Чиланзар": "Toshkent, Chilonzor",
    "Ташкент, Мирзо-Улугбек": "Toshkent, Mirzo Ulug'bek",
    "Ташкент, Сергели": "Toshkent, Sergeli",
    "Ташкент, Мирабад": "Toshkent, Mirobod",
    "Ташкент, Яккасарай": "Toshkent, Yakkasaroy",
    "Ташкент, Ойбек": "Toshkent, Oybek",
    "Ташкент, Центр": "Toshkent, Markaz",
    "Ташкент, Шайхантахур": "Toshkent, Shayxontohur",
    "Ташкент, Экопарк": "Toshkent, Ekopark",
    "Самарканд": "Samarqand",
    "Бухара": "Buxoro",
    "Андижан": "Andijon",
    "Наманган": "Namangan",
    "Фергана": "Farg'ona",
    "Нукус": "Nukus",
    "Удаленно": "Masofadan",
    "Удаленно / Ташкент": "Masofadan / Toshkent",

    // Tags
    "Трубы": "Quvurlar",
    "Электрик": "Elektrik",
    "Сборка мебели": "Mebel yig'ish",
    "Монтаж": "Montaj",
    "Люстры": "Qandillar",
    "Водопровод": "Suv quvurlari",
    "Прически": "Soch turmagi",
    "Свадьба": "To'y",
    "Гель-лак": "Gel-lak",
    "Барбер": "Barber",
    "Стрижки": "Soch kesish",
    "Борода": "Soqol",
    "Сайты": "Saytlar",
    "SMM": "SMM",
    "Таргет": "Target",
    "Дизайн": "Dizayn",
    "Логотипы": "Logotiplar",
    "Figma": "Figma",
    "Тексты": "Matnlar",
    "Копирайтинг": "Kopirayting",
    "Переводы": "Tarjimalar",
    "Бухгалтер": "Buxgalter",
    "Отчетность": "Hisobotlar",
    "Аутсорсинг": "Autsorsing",
    "Юрист": "Yurist",
    "Консультация": "Maslahat",
    "Суд": "Sud",
    "Похудение": "Ozish",
    "Бодибилдинг": "Bodibilding",
    "Здоровье": "Sog'liq",
    "Няня": "Enaga",
    "Дети": "Bolalar",
    "Помощница": "Yordamchi",
    "Химчистка": "Kimyoviy tozalash",
    "Мойка окон": "Deraza yuvish",
    "Водитель": "Haydovchi",
    "DJ": "DJ",
    "Фокусы": "Fokuslar",
    "Праздник": "Bayram",
    "Аниматор": "Animator",
    "IELTS": "IELTS",
    "Физика": "Fizika",
    "Фортепиано": "Fortepiano",

    // Specialist Descriptions
    "Репетитор по английскому языку (IELTS 8.5). Готовлю к поступлению в Вестминстер и ИНХА.": "Ingliz tili repetitori (IELTS 8.5). Westminster va INHA universitetlariga kirishga tayyorlayman.",
    "Математика для школьников 5-11 классов. Подготовка к ЕГЭ и ДТМ. Индивидуальный подход.": "5-11 sinf o'quvchilari uchun matematika. DTM ga tayyorgarlik. Individual yondashuv.",
    "Преподаватель фортепиано и сольфеджио. Опыт работы в консерватории 10 лет.": "Fortepiano va solfedjio o'qituvchisi. Konservatoriyada 10 yillik ish tajribasi.",
    "Опытный сантехник. Монтаж полипропиленовых труб, установка душевых кабин, ремонт смесителей. Работаю 24/7.": "Tajribali santexnik. Polipropilen quvurlarni montaj qilish, dush kabinalarini o'rnatish, kranlarni ta'mirlash. 24/7 ishlayman.",
    "Мастер универсал. Сантехника, электрика, сборка мебели. Опыт 10 лет. Даю гарантию.": "Universal usta. Santexnika, elektrika, mebel yig'ish. 10 yillik tajriba. Kafolat beraman.",
    "Профессиональный электрик с допуском. Монтаж проводки, установка люстр, щитков.": "Ruxsatnomaga ega professional elektrik. Simlarni montaj qilish, qandillar va shitlarni o'rnatish.",
    "Сантехник. Устранение засоров, установка смесителей, унитазов, ванн. Быстро и чисто.": "Santexnik. Tiqilib qolishlarni bartaraf etish, kranlar, unitazlar, vannalarni o'rnatish. Tez va toza.",
    "Визажист, стилист по прическам. Свадебный образ, вечерний макияж.": "Vizajist, soch turmagi ustasi. To'y obrazlari, oqshom makiyaji.",
    "Маникюр, педикюр, наращивание ногтей. Стерильные инструменты.": "Manikyur, pedikyur, tirnoq o'stirish. Steril asboblar.",
    "Мужские стрижки, оформление бороды. Выезд на дом.": "Erkaklar soch turmagi, soqol tekislash. Uyga borish xizmati.",
    "Разработка сайтов, настройка рекламы в Instagram и Telegram. Создание лендингов.": "Saytlar yaratish, Instagram va Telegram reklamalarini sozlash. Lendinglar yaratish.",
    "Графический дизайнер. Логотипы, фирменный стиль, баннеры, презентации.": "Grafik dizayner. Logotiplar, korporativ uslub, bannerlar, taqdimotlar.",
    "Написание продающих текстов для Instagram, статьи для сайтов, переводы RU/UZ/EN.": "Instagram uchun sotuvchi matnlar yozish, saytlar uchun maqolalar, RU/UZ/EN tarjimalari.",
    "Бухгалтерское сопровождение бизнеса, сдача отчетов, открытие ООО и ИП.": "Biznesni buxgalteriya hisobi bilan ta'minlash, hisobotlarni topshirish, MChJ va YaTT ochish.",
    "Юридические консультации. Семейное право, наследство, споры с застройщиками.": "Yuridik maslahatlar. Oila huquqi, meros, quruvchilar bilan nizolar.",
    "Персональный тренер по бодибилдингу и фитнесу. Составление программ питания.": "Bodibilding va fitnes bo'yicha shaxsiy murabbiy. Ovqatlanish dasturlarini tuzish.",
    "Инструктор по Хатха-йоге и стретчингу. Групповые и индивидуальные занятия.": "Hatha-yoga va stretching instruktori. Guruh va individual mashg'ulotlar.",
    "Няня для детей от 1 года. Добрая, ответственная, есть педагогическое образование.": "1 yoshdan oshgan bolalar uchun enaga. Mehribon, mas'uliyatli, pedagogik ma'lumotga ega.",
    "Профессиональная уборка квартир и офисов. Химчистка мягкой мебели.": "Kvartiralar va ofislarni professional tozalash. Yumshoq mebellarni kimyoviy tozalash.",
    "Личный водитель на своем авто (Malibu 2). Стаж вождения 15 лет. Пунктуальный.": "Shaxsiy avtomobilda haydovchi (Malibu 2). 15 yillik haydovchilik tajribasi. Mas'uliyatli.",
    "Музыкальное сопровождение свадеб, корпоративов, дней рождения. Своя аппаратура.": "To'ylar, korporativlar, tug'ilgan kunlarda musiqiy xizmat. Shaxsiy apparatura.",
    "Иллюзионист на детские праздники и взрослые мероприятия. Интерактивная программа.": "Bolalar bayramlari va kattalar tadbirlari uchun illyuzionist. Interaktiv dastur.",
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('ru');

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language;
    if (saved) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    // @ts-ignore
    const text = translations[language][key];
    if (text) return text;
    
    // Fallback to RU
    // @ts-ignore
    const fallbackText = translations['ru'][key];
    if (fallbackText) return fallbackText;

    // Fallback to key itself
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};